image: sim-docker.fzi.de/sim_rust

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cache
  QUICKCHECK_TESTS: 1000
  RUST_BACKTRACE: 1

cache: &general_cache
  paths:
    - cache/
    - Cargo.lock
  key:
    files:
      - Cargo.toml

stages:
  - build
  - test

cargo_build:
  stage: build
  tags:
    - docker
  script:
    - cargo build

check_spdx:
  stage: build
  tags:
    - docker
  script:
    - >
      find src -name '*.rs' | while read s; do
        grep -qx '// Copyright (c) 2021 FZI Forschungszentrum Informatik' $s || exit 1
        grep -qx '// SPDX-License-Identifier: Apache-2.0' $s || exit 1
      done
  cache:
    <<: *general_cache
    policy: pull

cargo_test:
  stage: test
  tags:
    - docker
  script:
    - cargo test
  cache:
    <<: *general_cache
    policy: pull

cargo_examples:
  stage: test
  tags:
    - docker
  script:
    - cargo build --examples
  cache:
    <<: *general_cache
    policy: pull

cargo_moddep:
  stage: test
  tags:
    - docker
  script:
    - mkdir firrtl_examples
    - wget "$FIRRTL_EXAMPLE_URI"
    - tar -C firrtl_examples  -xf *.tar.gz
    - cargo run --example moddep -- firrtl_examples/*.fir
  cache:
    <<: *general_cache
    policy: pull

