[package]
name = "firrtl-ast"
version = "0.1.0"
authors = ["Julian Ganz <ganz@fzi.de>"]
edition = "2018"

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"

[dependencies]
nom = "6.1"
num-bigint = "0.4"
num-traits = "0.2"
transiter = "0.1"
